using System;
using System.Collections.Generic;

namespace OpenTradeEngine;

public static partial class ExploreContentCatalog
{
    private static readonly Dictionary<string, IReadOnlyList<string>> FullHistoryPages = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Vexx"] =
        [
            "In 300 B.B., Mono Cheezo, a failed insurance salesman and amateur explorer, decided it was his destiny to seek out and discover new planets and achieve greatness and glory.  He sold his home, bought an ancient 200-ton dairy transport ship, hired a ragtag crew, and headed off for the far reaches of Gogg.\n\nAfter months of zig-zagging across the galaxy, he finally crashlanded on Vexx, an uncharted virgin planet, or so he thought.",
            "Elated at discovering a lush planet with an abundance of edible vegetation and no dangerous creatures, Mono Cheezo proclaimed Vexx the capital of Kukubia and himself the de facto King.\n\nWhat Mono Cheezo didn't realize was that Vexx had already been discovered by the dangerous cult of the Cylet Mind Buggers.  The Cylet Mind Buggers were feared throughout the galaxy for their deadly mental powers and strange eating habits.",
            "The Mind Buggers believed that by eating the brains of intelligent life forms, they could strengthen their own minds.\n\nOne by one, Mono Cheezo's crew began disappearing.  Thinking his crew had gone off to form their own government, Mono Cheezo declared them outlaws and banished them from his kingdom.\n\nIt wasn't until Mono Cheezo himself was captured and placed in a pot of boiling broth that he realized what was happening.",
            "Instead of panicking, Mono Cheezo calmly explained to these brain-eating fanatics that they could not possibly have him for dinner because he was the King of Kukubia and all creatures big and small living on Vexx were his subjects.\n\nThe more Mono Cheezo talked, the more the Cylet Mind Buggers began to lose their appetites.  After all, they believed that eating a madman could cause some serious brain damage.",
            "Taking Mono Cheezo out of the pot of boiling broth, the Mind Buggers told Mono Cheezo that they didn't want to eat him and he could go home.\n\nThe only problem was that Mono Cheezo didn't want to go home.  His entire crew was gone, and these cannibals were the only ones left on the planet.  Much to the Mind Buggers' dismay, Mono Cheezo moved in with them.",
            "The more comfortable Mono Cheezo became, the more he began to boss the Cylet Mind Buggers around.  As far as Mono was concerned, he was king and they were his subjects.\n\nThe Cylet Mind Buggers wanted to do away with Mono Cheezo, but it was against their religion to kill or in any way harm a living creature whose brain they were not prepared to eat.",
            "The Cylet Mind Buggers tried to escape several times.  They would wait until late at night when Mono Cheezo was asleep, then sneak away to another part of the planet.  However, sooner or later Mono Cheezo would find them.\n\nThis went on for months, until finally the Mind Buggers decided to bug out altogether.  Packing up everything, the Cylet Mind Buggers fled Vexx.",
            "Mono Cheezo remained alone on the planet for the next 130 years, until Supreme Commander Bass Nicolson (Emperor Dred's grandfather) and his army landed.\n\nWhen Bass Nicolson heard the story of how Mono Cheezo single-handedly drove the Mind Buggers from Vexx, he took pity on poor Mono and decided to make him the honorary governor of the planet.",
            "Like always, Mono Cheezo made himself at home and began ordering everyone around, including Supreme Commander Bass.  Within a few months, Bass had become so sick of Mono Cheezo's mandates that he banished Mono from Vexx and sent him to the Imperial Mental Institution.\n\nAs it happens, that is where Mono Cheezo met up with another infamous historical figure, Sir Lily Slimwagon, whose adventures are described in other sections.",
            "Ironically, Vexx became the capital of Kukubia as Mono had predicted, and to this day a statue of him stands in the courtyard of the Governor's Palace.",
        ],
        ["Pyke"] =
        [
            "The Hungo Warriors colonized Pyke 800 years before anyone in the New Realm ever heard of the planet.\n\nThe legendary Hungo Warriors were known throughout the galaxy for their ongoing war with the Army of the New Realm.  The Hungo won every battle they fought, but they were losing the war.  The Hungo were a small tribe.  Attrition had reduced them to a fraction of their original numbers, yet they continued to fight on.",
            "In 335 B.B. the Great Bass Nicolson (Emperor Dred Nicolson's grandfather) intensified his war against the Hungo and took over Pyke, one of their last strongholds in Gogg.\n\nThe weakened Hungo gradually retreated back into the Galaxy of Pata Pata Pita, allowing Bass Nicolson to consolidate his hold over Kukubia.",
            "Bass erected one of the first military outposts in Kukubia on Pyke.  Because he needed a ready supply of weapons and military machinery, Bass encouraged heavy industry to relocate to Pyke.\n\nThat is how L-Tech engines, the largest engine manufacturer came to the planet.  Originally L-Tech produced only military engines, but recently they have branched out, selling their engines to commercial traders.",
            "Pyke has been the target of a number of rebellions.\n\nThe first and best known of these is the Chichi Bobo uprising.  In 1 A.B. Chichi Bobo, an outspoken Imperial Senator and indigenous creatures rights supporter, broke from the Imperial rule of Hork Nicolson (Bass Nicolson's son and Dred Nicolson's father).  She proclaimed that the creatures of Gogg should speak up and oust the corrupt Nicolson family.",
            "With 10,000 supporters, mostly creatures native to Kukubia, Chichi Bobo stormed the military base on Pyke and took it over.  Holding 21 generals hostage, she demanded that Hork Nicolson resign and allow democratic elections.\n\nHork agreed to allow democratic elections on the local level, but refused to give up his position as Supreme Commander, since he felt it was his birthright.",
            "After a series of failed negotiations, Hork ordered a bloody assault on the base.  Chichi and her followers were annihilated.\n\nThis triggered a chain of events which destabilized the government and paralyzed Hork.  Unlike his father Bass, Hork was not too clever and could not figure out how to keep things under control.\n\nThe Mooglers, a motley group of anarchists, took to the streets protesting the government's brutal tactics.",
            "Fearing this uprising would spread to the rest of Gogg, Hork ordered the military to back off.\n\nSeeing Hork's weakness, the Mooglers became even more aggressive, burning banks, hospitals, schools and any other public institutions they deemed symbols of Imperial power. At the same time, groups of rebels began forming all across Gogg calling themselves the Chichi Bobo Freedom Fighters, after the martyred Chichi Bobo.",
            "With the New Realm disintegrating before their eyes, the Imperial Cabinet convened in secret and planned the assassination of Hork.  That night Hork was ambushed and killed on his way to Pyke.\n\nWith the Supreme Commander out of their way, the Cabinet Ministers took control and began a harsh crackdown on anyone opposing the government.  This worked for a time, until the various Ministers began arguing amongst themselves.",
            "For the next two decades the New Realm stagnated as Minister after Minister took control and was then deposed and executed.\n\nFinally, the military stepped in and reinstated Hork Nicolson's son, Dred Nicolson to the throne.  Dred, with the backing of the top generals, quickly dismissed the entire Imperial Cabinet and began remaking the system.",
            "His first symbolic act was to restart the Kukubian calendar beginning with his birthday.  He claimed to be the divine incarnation of his dead grandfather Bass Nicolson, and he believed that it gave him the right to do anything he pleased.\n\nWith the backing of the military, things quickly stabilized, and Dred, although far from brilliant, managed to bring some consistency to the vast New Realm.",
            "Over time, as the army's top generals became old and died, Dred felt comfortable enough to do away with martial law all together and grant independent merchants the right to trade inside Kukubia.",
        ],
        ["Mira"] =
        [
            "As far back as 1,000 B.B., Mira was awash in religious and spiritual energy.  The native creatures of Mira, the Quaso Mutta, are gelatinous blobs who spend days sitting on the green sandstone plains vibrating with Jaalesh (spiritual energy).  Their life is spent communicating in silence to the non-material world.\n\nThe Quaso Mutta would have gone on in their silent prayers uninterrupted if it had not been for one man, Lily Slimwagon.",
            "In 490 B.B., after being released from an Imperial Mental Institution, Lily Slimwagon, the infamous colonizer, claimed that he had received telepathic messages calling him back to Kukubia.\n\nAgainst Imperial orders, which forbade him from ever setting foot in Kukubia again, Lily organized an expedition to return to the Colonies.",
            "Lily's ill-fated expedition made several blunders, and he nearly starved to death before arriving on Mira.\n\nThere Lily encountered the Quaso Mutta.  These strange, silent creatures vibrating on the barren sandstone filled Lily with awe.  Unable to control his emotions, he broke down and wept begging them to forgive him for his past sins.  Of course, the Quaso Mutta ignored Lily's ranting and raving, but this didn't make a difference.",
            "Lily had found what he was looking for.  Lily proclaimed Mira the holiest planet in all of Gogg.\n\nAfter repairing his damaged ship, Lily began his long journey around the galaxy preaching the holy word of the Quaso Mutta.  Soon thousands of pilgrims began travelling to Mira in search of these mystical vibrating creatures.  The word spread, and the planet became known as a holy spot.  Churches began to spring up all over Mira.",
            "Various religious orders took form.  Some of the orders preached the art of meditation, while others sought to use the Quaso Mutta as oracles to predict the future.\n\nThe most renowned of the sects was the Grand Sages of Mira, who interpreted the vibrations of the Quaso Mutta to predict such famous events as Bass Nicolson's victory over the Pirates of Zile and the downfall of the Hapa Jillo Empire.\n\nOf course, for the Quaso Mutta, none of this mattered.",
            "After years of preaching and travelling, Lily finally returned to Mira.  Only Mira had changed.  It was no longer the serene, quiet home of the Quaso Mutta.  It was now a bustling planet filled with thousands of pilgrims, temples and shrines.\n\nBecause of the rapid change in the ecology of Mira, the majority of the Quaso Mutta silently died off.  The few Quaso Mutta left alive were kept locked inside the churches as sacred oracles.",
            "The sight of all this made Lily suddenly realize that he had succeeded in destroying another civilization.  In his horror, he fled Mira promising never to return to Kukubia again.\n\nMira continued to grow in popularity until it became a sort of institution throughout Gogg.  Even Supreme Commander Dred Nicolson now pays his respects to the Sages of Mira and asks for advice on everything from personal matters to politics.",
            "Unlike most of the other cults and religious sects, the Grand Sages were truly compassionate and learned monks.  It is only because of the Grand Sages that the Quaso Mutta were not totally wiped out.\n\nThe Grand Sages took the time to learn from and understand the Quaso Mutta.  This became the source of the Grand Sages power, and it enabled them to obtain an insight into how the non-material universe functions and the ability to influence the course of future events.",
        ],
        ["Stye"] =
        [
            "In 103 B.B., after the death of the great Bass Nicolson (Emperor Dred's grandfather), the Kukubian system was still forbidden to all but government spacecraft.  This was to prevent the re-emergence of pirates and other dangerous forces.  Although trade was limited, a few planets in Kukubia began to develop significant economies.\n\nOne of those was Stye, which rapidly grew into the financial capital of Kukubia.",
            "Stye was primarily populated by Soan Yatics, industrious and highly intellectual creatures who love money.\n\nThe Soan Yatics set up an ingenious system for transferring money across the galaxy using light wave emulation and communications technology.  Then the Soan Yatics transformed Stye into a tax haven, and banks began to relocate to the planet.",
            "The Soan Yatics took the excess capital and began investing it in local cities and institutions.\n\nOne of these institutions was the Traders' Union, which was instrumental in lobbying the Imperial Cabinet to open up Kukubia to independent merchants.  The Traders' Union set up strict banking and trading regulations detailing how commerce would function in Kukubia once trade by independent merchants was established.",
            "These rules and large amounts of investment capital reassured the skittish government that opening up Kukubia to private trading companies was in everyone's best interest.\n\nThus, when the government finally relaxed its stringent trade laws, the Traders' Union took on the responsibility of financing most of the start-up companies and regulating all transactions.  This self-regulation helped to minimize government interference in the Kukubian market.",
            "Today, Stye remains the financial center of the Kukubian system.  Almost all money flowing between Kukubia and the rest of the Galaxy of Gogg passes through Stye.\n\nThis has made the Soan Yatics wealthy and powerful.  They often wield more power over Kukubia than the Supreme Commander Dred Nicolson himself.",
            "The only difference is that the Soan Yatics operate discreetly without alerting anyone to their activities, while the brash Dred Nicolson makes a big deal out of every law or regulation he comes up with.\n\nThis means that often what the general population believes to be Imperial Mandates are actually the work of the Soan Yatics and their powerful lobbyists operating behind the scenes.",
        ],
        ["Loro"] =
        [
            "Loro became known as the Pleasure Planet because of the genius of Peelia Veelia, the leader of the Mamo Wuzzies.\n\nMamo Wuzzies are a race of bulky, energetic creatures who inhabited Loro before humans ever set foot in Kukubia.  Peelia Veelia saw the expansion of the New Realm as the perfect opportunity to satisfy her subject's basic needs.  You see, Mamo Wuzzies crave one thing in life, and that is stimulation.",
            "Mamo Wuzzies continually seek out new experiences, experimenting with everything they can get their sticky little hands on.\n\nFor example, if a new type of food is discovered, everyone rushes out to try it that very day.  However, within a week, a new fad takes over.  The most popular hairdo on Loro was only around for 13 days before it went out of style.",
            "This is why in 286 B.B., when Supreme Commander Bass Nicolson (Dred's grandfather) lead the Imperial Forces to Loro, he discovered a civilization unlike anything he had known before.\n\nThe Mamo Wuzzies embraced Bass and his soldiers with unparalleled enthusiasm.  They just couldn't get enough of the strange invaders and invited them to endless parties, celebrations, feasts and festivals.",
            "Bass' army found the Mamo Wuzzies fascinating as they constantly provided new sources of amusement.\n\nAs the Mamo Wuzzies entertained the soldiers, they continually sought out information about the Galaxy of Gogg and tried to learn everything they could from their visitors.  Peelia Veelia used this opportunity to convince Bass Nicolson to allow her to set up a galaxy-wide entertainment center.",
            "Peelia Veelia persuaded Bass that this would be mutually beneficial.  It would provide much-needed entertainment for the population of Gogg, create an additional source of tax revenue for the Imperial Government, and guarantee her people a constant source of stimulation.\n\nSeeing the great potential, Bass Nicolson agreed to help Peelia Veelia.  Thus, Loro became Gogg's best known resort destination.",
        ],
        ["Zile"] =
        [
            "Zile was colonized in 430 B.B. by a notorious pirate clan from Outer Glosser.\n\nThe leader of the clan, Bro Nap Goodshark, was an unscrupulous smuggler who dealt primarily in weapons and Agmal Juice.  The Imperial Government was hot on his trail, and he knew if he didn't leave Outer Glosser soon, the government would catch and hang him.  Zile seemed to be the perfect place to hide out and set up a new operation.",
            "Officially, the Kukubian system was still outside the New Realm.  Only two small colonies had been established inside Kukubia.\n\nWhen Bro Nap Goodshark landed on Zile, he quickly cut a deal with the local inhabitants, the Fez Fa Fa, a group of scab-ridden, green and yellow orifices with an appetite for animal flesh.  Bro Nap agreed to feed the Fez Fa Fa live humans and other choice creatures if they left him and his clan alone.",
            "Ever hungry for fresh flesh, the Fez Fa Fa agreed.  Bro Nap and his motley pirates hunted down defenseless cargo ships, stole their goods, and took the crews back to Zile as Fez Fa Fa food.\n\nFor the next 80 years, Bro Nap and his pirate clan operated with impunity attacking thousands of merchant ships.",
            "At the time, the New Realm was engaged in an all-out war with the Hapa Jillos from the Galaxy of Pata Pata Pita and could not spare the resources to go after Bro Nap.\n\nHowever, as soon as the Great Bass Nicolson (Emperor Dred's grandfather) defeated the Hapa Jillos, he focused all his attention on the internal problems of Gogg.\n\nBass Nicolson moved to expand the New Realm to include outlying territories like Kukubia.",
            "His goal was to guarantee safety and prosperity to all inhabitants of the galaxy.\n\nIn 349 B.B. Bass Nicolson's forces came head to head with Bro Nap's pirates in a bloody 8-year war.  The turning point was when the Fez Fa Fa broke off their alliance with Bro Nap and joined with the forces of Bass Nicolson to drive the pirates from Zile.",
            "After Bro Nap was killed defending his hoard of treasure, his clan split apart, and its members fled in all directions.  With Bass Nicolson's help, the Fez Fa Fa were moved to sanctuaries and fed a constant diet of livestock.\n\nToday they are considered relatively harmless, except for the occasional tourist who disappears around special Fez Fa Fa holidays.",
            "Under the new laws, only government ships were allowed to operate inside Kukubia.\n\nOld merchant families like Mr. Zinn's were permitted to set up businesses on each planet, but they were forbidden from owning or operating spacecraft of any kind.  This was necessary to keep control over the system and prevent the re-emergence of pirate activity.  It is only recently that Dred Nicolson opened up Kukubia to limited trade.",
            "Your company and a few other small trading firms are the first ones to be permitted to operate freely within the Colonies.  In order to prevent any one company from monopolizing the market, the Traders' Union has limited the amount Mr. Zinn and the other wealthy merchant families are allowed to invest.\n\nBecause of these restrictions, you and your competitors stand a good chance to make big bucks and expand with the growing Kukubian economies.",
        ],
        ["Frac"] =
        [
            "Frac was the first planet in the Kukubian system to be colonized.\n\nSir Lily Slimwagon, a fearless and somewhat eccentric explorer, arrived on Frac in 551 B.B., during the reign of Supreme Commander Bass Nicolson (Dred's grandfather).  He found a lush, tropical planet inhabited by Veggie Piddles, intelligent vegetable creatures who thrived on vine juice and lemon pudding.",
            "Instead of brutally forcing these little green beans into submission, which was the modus operandi of the time, Lily decided to wage a war of words.  Starting the next day, Lily and his army began jabbering away in a language the leafy creatures could not possibly understand.\n\nThe Veggies soon became so sick of listening to Lily and his soldiers babble that they decided to join the New Realm, if only to shut them up.",
            "As a gesture of gratitude toward their new Veggie brothers, Lily decreed that everyone (including himself and his soldiers) should pay tribute to the Veggie Piddles by eating nothing but lemon pudding, drinking wine of the vine, and wearing bright yellow clothing at all times.\n\nAt first this made for good foreign relations.  However, when Lily saw that the Veggie Piddles appreciated his gesture, he decided to take it one step further.",
            "Lily declared that yellow must be present in the consciousness of all citizens of Frac at all times.  He ordered all streets, buildings, cars and spacecraft painted yellow.  If anyone was caught sporting a color other than yellow, they would be banished from the planet for eternity.\n\nOf course, the Veggie Piddles were aghast at this new law, but they didn't know what to say since the law was made in an effort to please them.",
            "As the Veggie Piddles watched in horror, Lily and his soldiers began painting everything bright yellow, including the grass, trees, flowers, insects and every animal they could catch.\n\nSoon the entire planet was covered with a sickly coat of yellow paint.  Lily was so overtaken with his grand gesture that he was blind to what was happening to the planet.",
            "To celebrate the occasion, Lily decided to throw a massive party in honor of the Veggies.\n\nAs Lily prepared for this glorious event to celebrate Frac's union with the New Realm, a strange thing was taking place.  The toxins from the imported yellow paint began to penetrate all the plants and animals.  Within a matter of days, the lush green (yellow) landscape started to disappear.",
            "The Veggie Piddles scrambled to scrape the yellow paint off everything, but it was too late.  The planet was dying.  Lily and his soldiers couldn't understand why the Veggie Piddles were refusing to join in the celebration.\n\nIt was only after a week of wild merrymaking that it dawned on Lily something was wrong.  By that time most of the planet was dying.  Seeing the destruction he had caused, Lily became overwhelmed with grief.",
            "He had single-handedly destroyed an entire civilization when all he wanted to do was to help them.  In the midst of a nervous breakdown, Lily was dragged off the dying planet and committed to an Imperial Mental Institution.\n\nAs time passed, the atrocities were forgotten and Frac was transformed into a thriving commercial zone.",
            "Under the powerful rule of Supreme Commander Bass Nicolson (Dred's grandfather), the New Realm expanded into Kukubia, and Frac became a crucial trading center.\n\nNow it is home to numerous commercial institutions such as Gizzy Shipping, Roke Transport and Voyager's Insurance Company.\n\nHowever, even to this day, Lily's legacy exists.  Frac has never regained its tropical forests.",
            "Frac is still a stark desert planet, and without their supply of vine juice and lemon pudding, all the Veggie Piddles have long since perished.\n\nThe only testament to their ancient civilization is the bright yellow sand which covers 90% of the planet.",
        ],
        ["Tilo"] =
        [
            "Tilo is the only planet in the Kukubian System with legalized gambling.  Supreme Commander Dred Nicolson detests gambling and has outlawed casinos in most major cities.\n\nEmperor Dred is opposed to gambling for two reasons.  First, casinos take money away from the general public, and Dred would much rather the public spend its hard earned money on taxes, which go directly to him, than gambling, which lines the pockets of the casino owners.",
            "The second reason for Dred's opposition to organized gambling is that 99% of all the casinos in Gogg are controlled by the Hapa Jillo Syndicate, a longtime enemy of the Nicolson Dynasty.\n\nThe Hapa Jillos are a race of highly intelligent and ruthless creatures from the neighboring Galaxy of Pata Pata Pita.\n\nAlthough, the Great Bass Nicolson (Dred's grandfather) defeated the Hapa Jillo Empire in 350 B.B. and drove most of the Hapa Jillo population out of Gogg, several million Hapa Jillos remained behind, scattered throughout the galaxy.",
            "Because they were not accepted by society, many turned to lives of crime, including racketeering, money laundering, and running illegal gambling operations.  Some of the small operations grew so prosperous that they literally took over planets like Tilo.\n\nBefore the Nicolson Family realized what was happening, it was too late.  The casinos had become a fixture in certain areas and could not be removed.",
            "Typically, whenever Dred tried to shut down a casino, local political leaders and business owners would become so furious that they often threatened a revolt.  Dred decided his next best option was containment.  That is why gambling has been restricted to one or two planets in each system.\n\nIn Kukubia, that planet is Tilo.  If someone wants to gamble, they must travel to Tilo.  In fact, gambling has become such a vital part of Tilo's economy that it accounts for 80% of planet's revenue.",
            "However, even on Tilo, gambling is regulated.\n\nNo one is allowed to gamble more than 5% of their total cash in one week.  This was Dred's latest effort to curb gambling and gradually erode the power of the Hapa Jillo Syndicate.",
        ],
        ["Queg"] =
        [
            "Queg is the infamous renegade planet.  It is here that the galaxy's most notorious gangsters come to unload their wares.\n\nEveryone from Scooter Jay to the Baid-Rowel Bandits routinely visit Queg.  A powerful warlord, who goes by the name of Lady Cornucopia, rules the planet and brokers all transactions.\n\nBecause Emperor Dred Nicolson needs Lady Cornucopia in his on-going skirmish with the Hapa Jillos, he tolerates her illicit activities.",
            "If Emperor Dred Nicolson had his way, Queg would be firmly under the control of the Imperial Magistrate, all smuggling activities would cease, and every transaction would be heavily taxed.\n\nHowever, Lady Cornucopia commands a large standing army, and she has been using this army as a deterrent against a possible Hapa Jillo invasion.  If she were to become upset with Dred Nicolson and ally herself with the Hapa Jillos, it would literally mean the end of Kukubia as we know it.",
            "History shows that the Hapa Jillo Empire once included all of Kukubia along with a huge portion of western Gogg.\n\nIt is only after the Great Bass Nicolson (Emperor Dred's grandfather) gloriously defeated the Hapa Jillo Armada and took full control of Kukubia that the Hapa Jillos retreated back to the neighboring galaxy of Pata Pata Pita.   Although the Hapa Jillos have never regained their former power, they still command a sizable army.",
            "In recent years, the Hapa Jillos have become increasingly bold.  They often make raids on outlying planets and merchant ships which stray into their territory.\n\nWe can only hope that the agreement between Lady Cornucopia and Dred Nicolson holds.  Otherwise, Kukubia may become the focal point of a long, destructive war.",
        ],
        ["Xeen"] =
        [
            "Xeen is one giant junkyard filled with spare parts and brilliant mechanics.\n\nXeen got its start after the Great Bass Nicolson (Emperor Dred Nicolson's grandfather) defeated the Hapa Jillo Empire.  Bass needed some place to dump all of his old and battered battle ships.  Since Xeen wasn't a very hospitable planet and had no native intelligent life forms, it seemed the natural place for a junk-yard.\n\nAs time went on, everyone began dumping their garbage on Xeen.",
            "Out of this trash heap sprung an entire industry focused on repairing and rebuilding machines.  Xeen is now the central location for all ship repairs, upgrades and construction in Kukubia.\n\nThe mechanics on Xeen are so ingenious that they are constantly coming up with new inventions and ways of improving upon existing technology.\n\nThis has made Xeen into a vital part of the Kukubian economy and the only planet where you can find things like a rebuilt toaster that substitutes as a toothbrush.",
        ],
        ["Ooom"] =
        [
            "Ooom is known throughout the Kukubian System as the Fortune Teller's Planet.  This is because the Soothsayers, a mysterious breed of creatures who live only on Ooom, have the uncanny ability to predict the future by scanning one's aura for positive or negative energy.\n\nAs far back as 400 B.B., the Great Bass Nicolson (Dred's Grandfather) would consult the Soothsayers of Ooom before entering into any battle.  This may account in part for Bass' victory over the Hapa Jillo Empire.",
            "Today, Ooom is a destination spot for business owners from all over Gogg.  They come to Ooom to find out what their energy level is, so that they know whether or not to purchase insurance, conduct a risky transaction, or make a major business decision.\n\nThe Soothsayers have a reputation for being eccentric.  They will often experiment on their clients, either to try to achieve the best results or just for their own amusement.",
            "The Soothsayer's power is believed to stem from some connection between their unique body chemistry and the planet's electro-chemical composition.\n\nIn fact, if a Soothsayer is removed from Ooom, not only will they be unable to make a prediction, but they usually perish within a few months.  Their bodies simply cease to function.  No one has been able to figure out why this happens.",
            "However, a team of scientists, who would like to enable the Soothsayers to travel to other planets, are researching this phenomenon.\n\nOne thing that should be pointed out is that the Soothsayer's advice is not set in stone.  In fact, the aura readings are only an indication of what may come.  It is as if they are interpreting statistical data on the probability that good or bad luck will occur.",
            "If a Soothsayer says your aura is positive and you will have good fortune, this actually means your chances of having good fortune far outweigh your chances of experiencing bad luck.\n\nHowever, there is still a small chance that you may run into an unfavorable situation despite a rather positive reading.",
        ],
        ["Hork"] =
        [
            "The planet Hork is named after Emperor Hork Nicolson (Emperor Dred Nicolson's father).\n\nHork Nicolson originally saw this planet as the hub of his propaganda machine.  At the time, he was losing control of the Kukubian Colonies and was in need of help.  The only problem was that Hork Nicolson was not nearly as intelligent as his father, the Great Bass Nicolson, and his efforts at regulating all media and cramming political slogans down everyone's throat only made the rebellious colonies even more upset.",
            "After Emperor Hork was assassinated by his own cabinet, the entire New Realm began to disintegrate.\n\nWith this collapse came new liberties.  For the first time in the Nicolson Dynasty, the media had complete freedom of speech.  Consequently, planet Hork began to flourish as a cultural and artistic center.  In those few years, the print, TV and film industries blossomed.\n\nIt wasn't until the reinstatement of Dred Nicolson to the throne that things began to tighten up again.",
            "Today, the media is still much freer than in the time of Emperor Hork, but there are certain lines journalists dare not cross.\n\nThese regulations, however, have not prevented the planet Hork from retaining its place as the media capital of the Colonies.  It is presently where 90% of Kukubia's films, TV shows, magazines and newspapers are produced.\n\nIf a business needs some publicity, planet Hork is the place to be.",
        ],
        ["Bass"] =
        [
            "Bass is named after the Great Bass Nicolson (Dred Nicolson's grandfather).\n\nAfter Bass Nicolson defeated the Hapa Jillo Empire and the Pirates of Zile, he began transporting all of the treasures he had plundered and pillaged to this planet.\n\nAlong with these treasures came a legion of accountants, merchants and financial types, whose duty it was to catalog everything, sell off the valuable items, and invest the profits in emerging markets throughout the galaxy.",
            "To facilitate this huge transfer of wealth, the first Galactic Stock Exchange was established.  It tracked markets all across the New Realm, set up branch offices on every major planet, and created numerous new investment opportunities.  This influx of wealth fueled the growth of colonies like Kukubia.\n\nStock brokers, market analysts and traders congregated on Bass to exchange information and plan their investment strategies.",
            "After the original treasures were all sold, the importance of the Galactic Stock Exchange declined.  By this time, other stock exchanges had sprung up all across the Galaxy of Gogg.  Thus, the Galactic Stock Exchange had to be renamed the Kukubian Stock Exchange, and its main focus became the 7 planets of the Kukubian System.\n\nToday, if an investor wants advice on the Kukubian market, Bass is the best place to go.",
        ],
        ["Nosh"] =
        [
            "The Quaso Mutta have revealed that millions of years ago, Nosh used to be a small star.  The planet was literally a ball of fire, fueled by its own super-heated core.\n\nHowever, when a rare solar snow storm collided with the planet, showering it with ice, the fire on the planet's surface was extinguished.  The planet naturally cooled over the next million years, leaving behind huge fuel reservoirs.\n\nThat fuel is what drove the initial expansion of the New Realm and helped to make Kukubia into a thriving colony.",
            "The irony is that today Nosh doesn't produce enough fuel to meet its own needs and must import 99% of its energy.\n\nJust a hundred years ago, Nosh was actually producing most of the fuel consumed in the western half of Gogg.  However, this natural resource was so recklessly managed that within a short time the planet went dry.\n\nToday, all fuel must be imported to Kukubia using large tankers.  This accounts, in part, for the high fuel prices and erratic supply.",
            "When a fuel tanker enters Kukubia, it typically lands on Nosh, where the raw fuel is unloaded, refined and stored.\n\nIn most parts of Kukubia, the price of fuel is fixed.  However, on Nosh, you can almost always find a wholesaler, who will sell you the fuel at a discounted price.\n\nThis is why most merchant ships have incorporated Nosh into their trade routes.",
        ],
    };
}

